import { Router } from "express";
import authRouter from "./auth";
import usersRouter from "./users";
import projectsRouter from "./projects";
import eventsRouter from "./events";
import membersRouter from "./members";
import chaptersRouter from "./chapters";
import committeesRouter from "./committees";
import webhooksRouter from "./webhooks";
import donationsRouter from "./donations";
import transactionsRouter from "./transactions";
import shopRouter from "./shop";
import announcementsRouter from "./announcements";
import applicationsRouter from "./applications";
import duesRouter from "./dues";
import partnershipsRouter from "./partnerships";
import welfareRouter from "./welfare";
import dashboardRouter from "./dashboard";
import constituentsRouter from "./constituents";

const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use("/projects", projectsRouter);
apiRouter.use("/events", eventsRouter);
apiRouter.use("/members", membersRouter);
apiRouter.use("/chapters", chaptersRouter);
apiRouter.use("/committees", committeesRouter);
apiRouter.use("/webhooks", webhooksRouter);
apiRouter.use("/donations", donationsRouter);
apiRouter.use("/transactions", transactionsRouter);
apiRouter.use("/shop", shopRouter);
apiRouter.use("/announcements", announcementsRouter);
apiRouter.use("/applications", applicationsRouter);
apiRouter.use("/dues", duesRouter);
apiRouter.use("/partnerships", partnershipsRouter);
apiRouter.use("/welfare", welfareRouter);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/constituents", constituentsRouter);

export default apiRouter;
