import {
  pgSchema,
  uuid,
  timestamp,
  decimal,
  integer,
  text,
  unique,
  index,
} from "drizzle-orm/pg-core";
import { Committees, Constituents } from "./core";

export const logs = pgSchema("logs");

/**
 * Monthly reports table - stores aggregated statistics for each month.
 * Generated by the GENERATE_MONTHLY_REPORT job that runs on the 1st of each month.
 * All columns are nullable to handle cases where data might not be available.
 */
export const MonthlyReports = logs.table("monthly_reports", {
  id: uuid().defaultRandom().primaryKey(),

  // Report period (first day of the month the report covers)
  reportMonth: timestamp("report_month", { withTimezone: true })
    .notNull()
    .unique(),

  // Financial metrics
  totalDonations: decimal("total_donations", { precision: 12, scale: 2 }),
  donationsCount: integer("donations_count"),
  totalDuesPayments: decimal("total_dues_payments", {
    precision: 12,
    scale: 2,
  }),
  duesPaymentsCount: integer("dues_payments_count"),
  totalOrderPayments: decimal("total_order_payments", {
    precision: 12,
    scale: 2,
  }),
  orderPaymentsCount: integer("order_payments_count"),

  // Onboarding metrics
  newMembersCount: integer("new_members_count"),
  newVolunteersCount: integer("new_volunteers_count"),

  // Activity metrics
  eventsCount: integer("events_count"),
  projectsCount: integer("projects_count"),
  announcementsCount: integer("announcements_count"),

  // Metadata
  generatedAt: timestamp("generated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});

export const WorkspaceSubmissionKindEnum = logs.enum(
  "workspace_submission_kind",
  ["PLAN", "REPORT"],
);

export const WorkspaceNoteEntityTypeEnum = logs.enum(
  "workspace_note_entity_type",
  ["program", "event", "workspace"],
);

export const WorkspaceMonthlySubmissions = logs.table(
  "workspace_monthly_submissions",
  {
    id: uuid().defaultRandom().primaryKey(),
    committeeId: uuid("committee_id")
      .notNull()
      .references(() => Committees.id, { onDelete: "cascade" }),
    month: timestamp("month", { withTimezone: true }).notNull(),
    kind: WorkspaceSubmissionKindEnum().notNull(),
    body: text().notNull(),
    documentName: text("document_name"),
    documentUrl: text("document_url"),
    submittedBy: uuid("submitted_by")
      .notNull()
      .references(() => Constituents.id, { onDelete: "restrict" }),
    submittedAt: timestamp("submitted_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    unique().on(table.committeeId, table.month, table.kind),
    index("idx_workspace_submissions_committee_month").on(
      table.committeeId,
      table.month,
    ),
  ],
);

export const WorkspaceNotes = logs.table(
  "workspace_notes",
  {
    id: uuid().defaultRandom().primaryKey(),
    committeeId: uuid("committee_id")
      .notNull()
      .references(() => Committees.id, { onDelete: "cascade" }),
    entityType: WorkspaceNoteEntityTypeEnum("entity_type").notNull(),
    entityId: uuid("entity_id"),
    body: text().notNull(),
    authorId: uuid("author_id")
      .notNull()
      .references(() => Constituents.id, { onDelete: "restrict" }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
  },
  (table) => [
    index("idx_workspace_notes_entity").on(
      table.committeeId,
      table.entityType,
      table.entityId,
    ),
  ],
);
