import {
  pgSchema,
  uuid,
  timestamp,
  decimal,
  integer,
} from "drizzle-orm/pg-core";

export const logs = pgSchema("logs");

/**
 * Monthly reports table - stores aggregated statistics for each month.
 * Generated by the GENERATE_MONTHLY_REPORT job that runs on the 1st of each month.
 * All columns are nullable to handle cases where data might not be available.
 */
export const MonthlyReports = logs.table("monthly_reports", {
  id: uuid().defaultRandom().primaryKey(),

  // Report period (first day of the month the report covers)
  reportMonth: timestamp("report_month", { withTimezone: true })
    .notNull()
    .unique(),

  // Financial metrics
  totalDonations: decimal("total_donations", { precision: 12, scale: 2 }),
  donationsCount: integer("donations_count"),
  totalDuesPayments: decimal("total_dues_payments", {
    precision: 12,
    scale: 2,
  }),
  duesPaymentsCount: integer("dues_payments_count"),
  totalOrderPayments: decimal("total_order_payments", {
    precision: 12,
    scale: 2,
  }),
  orderPaymentsCount: integer("order_payments_count"),

  // Onboarding metrics
  newMembersCount: integer("new_members_count"),
  newVolunteersCount: integer("new_volunteers_count"),

  // Activity metrics
  eventsCount: integer("events_count"),
  projectsCount: integer("projects_count"),
  announcementsCount: integer("announcements_count"),

  // Metadata
  generatedAt: timestamp("generated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});
